using Vogen;

namespace MediatrUnionPoc.Domain;

/// <summary>
/// A <see cref="Guid"/>-backed identity for <see cref="Product"/>. Generated by Vogen from the
/// <c>[ValueObject]</c> attribute — <see cref="Validate"/> is called from every generated
/// factory (<c>From</c>, <c>TryFrom</c>) so an empty guid can never enter the system, and
/// equality/hashing/<see cref="ToString()"/> are all structural rather than reference-based.
/// Serializes as a bare GUID string (see <see cref="Conversions.SystemTextJson"/>), not as an
/// object — the Infrastructure layer's <c>ProductIdValueConverter</c> handles the equivalent
/// round-trip through EF Core instead.
/// </summary>
[ValueObject<Guid>(conversions: Conversions.SystemTextJson)]
public readonly partial struct ProductId
{
    /// <summary>Invoked by every Vogen-generated factory method; rejects <see cref="Guid.Empty"/>.</summary>
    private static Validation Validate(Guid input) =>
        input != Guid.Empty
            ? Validation.Ok
            : Validation.Invalid("ProductId cannot be an empty guid.");

    /// <summary>Generates a fresh, guaranteed-valid identity for a new <see cref="Product"/>.</summary>
    /// <returns>A new, non-empty <see cref="ProductId"/>.</returns>
    public static ProductId New() => From(Guid.NewGuid());
}
